// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Endpoints from "../Endpoints.mjs";
import * as FetchTools from "../FetchTools.mjs";
import * as Decode$Shared from "@brightidbot/shared/src/Decode.mjs";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.mjs";

async function getAppInfo(nodesOpt, context) {
  var nodes = nodesOpt !== undefined ? nodesOpt : Endpoints.nodes;
  var json = await FetchTools.fetchJson("/apps/" + context, nodes);
  var match = FetchTools.decodeResponse(json, Decode$Shared.Decode_BrightId.App.data);
  var data = match.data;
  if (data.id !== context || data.context !== context) {
    throw {
          RE_EXN_ID: Json_Decode$JsonCombinators.DecodeError,
          _1: "BrightID application does not match the requested app",
          Error: new Error()
        };
  }
  return data;
}

export {
  getAppInfo ,
}
/* Endpoints Not a pure module */
