// Generated by ReScript, PLEASE EDIT WITH CARE


var noContent = 204;

var notSponsoredCode = 403;

var notFoundCode = 404;

var errorCode = 500;

var contextNotFound = 1;

var contextidNotFound = 2;

var canNotBeVerified = 3;

var notSponsored = 4;

export {
  noContent ,
  notSponsoredCode ,
  notFoundCode ,
  errorCode ,
  contextNotFound ,
  contextidNotFound ,
  canNotBeVerified ,
  notSponsored ,
  
}
/* No side effect */
