const NO_CONTENT = 204
const NOT_SPONSORED_CODE = 403
const NOT_FOUND_CODE = 404
const ERROR_CODE = 500

const CONTEXT_NOT_FOUND = 1
const CONTEXTID_NOT_FOUND = 2
const CAN_NOT_BE_VERIFIED = 3
const NOT_SPONSORED = 4

module.exports = {
  NO_CONTENT,
  NOT_SPONSORED_CODE,
  NOT_FOUND_CODE,
  ERROR_CODE,
  CONTEXT_NOT_FOUND,
  CONTEXTID_NOT_FOUND,
  CAN_NOT_BE_VERIFIED,
  NOT_SPONSORED,
}
