// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Env = require("../Env.bs.js");
var Dotenv = require("dotenv");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.bs.js");
var Constants = require("../Constants.bs.js");
var Endpoints = require("../Endpoints.bs.js");
var NodeFetch = require("node-fetch");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");
var Handlers_Verify = require("../handlers/Handlers_Verify.bs.js");
var Discord_Snowflake = require("../Discord/Discord_Snowflake.bs.js");
var Services_ResponseCodes = require("./Services_ResponseCodes.bs.js");

var VerificationInfoError = /* @__PURE__ */Caml_exceptions.create("Services_VerificationInfo.VerificationInfoError");

var FetchVerificationInfoError = /* @__PURE__ */Caml_exceptions.create("Services_VerificationInfo.FetchVerificationInfoError");

Dotenv.config();

var config = Env.getConfig(undefined);

var uuidNAMESPACE;

if (config.TAG === /* Ok */0) {
  uuidNAMESPACE = config._0.uuidNamespace;
} else {
  throw {
        RE_EXN_ID: VerificationInfoError,
        _1: config._0,
        Error: new Error()
      };
}

var $$Response = {};

var defaultVerification_userAddresses = [];

var defaultVerification = {
  authorExist: false,
  authorUnique: false,
  timestamp: 0,
  userAddresses: defaultVerification_userAddresses,
  userVerified: false,
  fetching: false
};

function fetchVerificationInfo(retryOpt, id) {
  var retry = retryOpt !== undefined ? retryOpt : 5;
  var id$1 = Handlers_Verify.UUID.v5(/* UUIDName */{
        _0: id
      }, uuidNAMESPACE);
  var endpoint = Endpoints.brightIdVerificationEndpoint + "/" + Constants.contextId + "/" + id$1 + "?timestamp=seconds";
  var params = {
    method: "GET",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    },
    timestamp: 60000
  };
  return $$Promise.$$catch(NodeFetch(endpoint, params).then(function (prim) {
                    return prim.json();
                  }).then(function (res) {
                  var data = res.data;
                  if (data == null) {
                    var match = res.code;
                    var match$1 = res.errorMessage;
                    var match$2 = res.errorNum;
                    if (match == null) {
                      return Promise.reject({
                                  RE_EXN_ID: VerificationInfoError,
                                  _1: "No code or errorMessage"
                                });
                    } else if (match$1 == null) {
                      return Promise.reject({
                                  RE_EXN_ID: VerificationInfoError,
                                  _1: "No code or errorMessage"
                                });
                    } else if (match$2 == null) {
                      return Promise.reject({
                                  RE_EXN_ID: VerificationInfoError,
                                  _1: "No code or errorMessage"
                                });
                    } else {
                      return Promise.reject({
                                  RE_EXN_ID: FetchVerificationInfoError,
                                  error: match$1,
                                  fetching: false
                                });
                    }
                  }
                  var match$3 = data.unique;
                  var match$4 = data.timestamp;
                  var match$5 = data.contextIds;
                  if (!(match$3 == null) && !(match$4 == null) && !(match$5 == null)) {
                    return Promise.resolve({
                                authorExist: true,
                                authorUnique: match$3,
                                timestamp: match$4,
                                userAddresses: match$5,
                                userVerified: true,
                                fetching: false
                              });
                  } else {
                    return Promise.reject({
                                RE_EXN_ID: VerificationInfoError,
                                _1: "Necessary Verification Info missing after successful fetch "
                              });
                  }
                }), (function (e) {
                if (e.RE_EXN_ID === VerificationInfoError) {
                  console.error(e._1);
                } else if (e.RE_EXN_ID === FetchVerificationInfoError) {
                  console.error("Fetch Verification Info Error: " + e.error);
                } else if (e.RE_EXN_ID === $$Promise.JsError) {
                  var msg = e._1.message;
                  if (msg !== undefined) {
                    console.error(msg);
                  } else {
                    console.error("Must be some non-error value");
                  }
                } else {
                  console.error("Some unknown error");
                }
                var retry$1 = retry - 1 | 0;
                if (retry$1 !== 0) {
                  return fetchVerificationInfo(retry$1, id$1);
                } else {
                  return Promise.resolve(defaultVerification);
                }
              }));
}

function getBrightIdVerification(member) {
  var id = Discord_Snowflake.validateSnowflake(member.id);
  return fetchVerificationInfo(undefined, id);
}

var contextId = Constants.contextId;

var brightIdVerificationEndpoint = Endpoints.brightIdVerificationEndpoint;

var notFoundCode = Services_ResponseCodes.notFoundCode;

var errorCode = Services_ResponseCodes.errorCode;

var canNotBeVerified = Services_ResponseCodes.canNotBeVerified;

var verificationPollingEvery = 3000;

var requestTimeout = 60000;

exports.VerificationInfoError = VerificationInfoError;
exports.FetchVerificationInfoError = FetchVerificationInfoError;
exports.config = config;
exports.uuidNAMESPACE = uuidNAMESPACE;
exports.$$Response = $$Response;
exports.contextId = contextId;
exports.brightIdVerificationEndpoint = brightIdVerificationEndpoint;
exports.notFoundCode = notFoundCode;
exports.errorCode = errorCode;
exports.canNotBeVerified = canNotBeVerified;
exports.verificationPollingEvery = verificationPollingEvery;
exports.requestTimeout = requestTimeout;
exports.defaultVerification = defaultVerification;
exports.fetchVerificationInfo = fetchVerificationInfo;
exports.getBrightIdVerification = getBrightIdVerification;
/*  Not a pure module */
