// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@remix-run/react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var ReactDOM = {};

function hydrate(param) {
  React.startTransition(function (param) {
        Client.hydrateRoot(document, JsxRuntime.jsx(React.StrictMode, {
                  children: JsxRuntime.jsx(React$1.RemixBrowser, {})
                }));
      });
}

export {
  ReactDOM ,
  hydrate ,
}
/* react Not a pure module */
