// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Sponsorships_Index$default(Props) {
  return React.createElement("div", undefined, "Hello, world!");
}

var $$default = Sponsorships_Index$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
