// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Remix from "remix";
import * as Js_dict from "../../../../../node_modules/rescript/lib/es6/js_dict.js";
import * as $$Promise from "../../../../../node_modules/@ryyppy/rescript-promise/src/Promise.js";
import * as AuthServer from "../../AuthServer.js";
import * as Belt_Option from "../../../../../node_modules/rescript/lib/es6/belt_Option.js";
import * as Caml_option from "../../../../../node_modules/rescript/lib/es6/caml_option.js";
import * as Webapi__Fetch from "../../../../../node_modules/rescript-webapi/src/Webapi/Webapi__Fetch.js";
import * as Caml_exceptions from "../../../../../node_modules/rescript/lib/es6/caml_exceptions.js";
import * as UpdateOrReadGistJs from "../../helpers/updateOrReadGist.js";

var EmptySubmit = /* @__PURE__ */Caml_exceptions.create("Guilds_AdminSubmit.EmptySubmit");

function updateGist(prim0, prim1) {
  return UpdateOrReadGistJs.updateGist(prim0, prim1);
}

var botToken = process.env.DISCORD_API_TOKEN;

function loader(param) {
  var guildId = Belt_Option.getWithDefault(Js_dict.get(param.params, "guildId"), "0x");
  return Promise.resolve(Remix.redirect("/guilds/" + guildId + "/admin"));
}

function urlModifyRole(guildId, roleId) {
  return "/guilds/" + guildId + "/roles/" + roleId + "";
}

function action(param) {
  var request = param.request;
  var guildId = Belt_Option.getWithDefault(Js_dict.get(param.params, "guildId"), "0x");
  return AuthServer.authenticator.isAuthenticated(request).then(function (user) {
              return $$Promise.$$catch(request.formData().then(function (data) {
                              var headers = {
                                Authorization: "Bot " + botToken + ""
                              };
                              var init = Webapi__Fetch.RequestInit.make(/* Patch */8, Caml_option.some(headers), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined);
                              return fetch(new Request(urlModifyRole(guildId, "roleId"), init)).then(function (res) {
                                          var role = data.get("role");
                                          var inviteLink = data.get("inviteLink");
                                          if (role !== undefined && inviteLink !== undefined) {
                                            return UpdateOrReadGistJs.updateGist(guildId, {
                                                        role: Caml_option.valFromOption(role),
                                                        inviteLink: Caml_option.valFromOption(inviteLink)
                                                      });
                                          } else {
                                            return Promise.reject({
                                                        RE_EXN_ID: EmptySubmit
                                                      });
                                          }
                                        });
                            }), (function (e) {
                            if (e.RE_EXN_ID === EmptySubmit) {
                              Remix.redirect("/guilds/" + guildId + "/admin");
                              return Promise.resolve(undefined);
                            } else {
                              Remix.redirect("/guilds/" + guildId + "/admin");
                              return Promise.resolve(undefined);
                            }
                          }));
            });
}

export {
  EmptySubmit ,
  updateGist ,
  botToken ,
  loader ,
  urlModifyRole ,
  action ,
}
/* botToken Not a pure module */
