// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Remix from "remix";
import * as Wagmi from "wagmi";
import * as SidebarToggle from "../../components/SidebarToggle.js";
import * as SponsorshipsModal from "../../components/SponsorshipsModal.js";

function Guilds_Sponsor$default(Props) {
  var context = Remix.useOutletContext();
  var match = Remix.useSearchParams();
  if (match.length !== 1) {
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Guilds_Sponsor.res",
            9,
            6
          ],
          Error: new Error()
        };
  }
  var searchParams = match[0];
  Wagmi.useSignMessage({
        message: "I am the owner of and would like to use its sponsorhips in\n    X"
      });
  var match$1 = searchParams.get("setup_sponsorships");
  var sponsorshipModal = (match$1 == null) ? React.createElement(React.Fragment, undefined) : React.createElement(SponsorshipsModal.make, {});
  return React.createElement("div", {
              className: "p-4 h-full w-full"
            }, React.createElement(SidebarToggle.make, {
                  handleToggleSidebar: context.handleToggleSidebar
                }), "Layout", React.createElement("div", undefined, React.createElement(Remix.Outlet, {})), sponsorshipModal);
}

var $$default = Guilds_Sponsor$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
