// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function validateGuildName(guildName) {
  return guildName._0;
}

function make(guild) {
  var id = guild.id;
  var name = guild.name;
  var roles = guild.roles;
  return {
          id: /* Snowflake */{
            _0: id
          },
          name: /* GuildName */{
            _0: name
          },
          roles: roles
        };
}

exports.validateGuildName = validateGuildName;
exports.make = make;
/* No side effect */
