// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Discord_RoleManager = require("./Discord_RoleManager.bs.js");

function validateGuildName(guildName) {
  return guildName._0;
}

function make(guild) {
  var id = guild.id;
  var name = guild.name;
  var roles = guild.roles;
  return {
          id: /* Snowflake */{
            _0: id
          },
          name: /* GuildName */{
            _0: name
          },
          roles: Discord_RoleManager.make(roles)
        };
}

exports.validateGuildName = validateGuildName;
exports.make = make;
/* No side effect */
