// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function send(guildMember, content, options) {
  return guildMember.t.send(content, options);
}

exports.send = send;
/* No side effect */
