// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DiscordJs = require("discord.js");

function make(param) {
  var client = new DiscordJs.Client(undefined);
  return /* Client */{
          _0: client
        };
}

function validateClient(client) {
  return client._0;
}

function login(client, token) {
  client._0.login(token._0);
  
}

exports.make = make;
exports.validateClient = validateClient;
exports.login = login;
/* discord.js Not a pure module */
