// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function validateRoleName(name) {
  return name._0;
}

function make(role) {
  var name = role.name;
  return {
          name: /* RoleName */{
            _0: name
          }
        };
}

exports.validateRoleName = validateRoleName;
exports.make = make;
/* No side effect */
