// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("@ryyppy/rescript-promise/src/Promise.bs.js");

function validateEmojiName(name) {
  return name._0;
}

function validateContent(content) {
  return content._0;
}

function reply(message, options) {
  var content = typeof options === "number" ? "" : options._0;
  return $$Promise.$$catch(message.t.reply(content), (function (e) {
                if (e.RE_EXN_ID === $$Promise.JsError) {
                  var msg = e._1.message;
                  if (msg !== undefined) {
                    console.error(msg);
                  } else {
                    console.error("Must be some non-error value");
                  }
                } else {
                  console.error("Some unknown error");
                }
                return Promise.resolve(message.t);
              }));
}

exports.validateEmojiName = validateEmojiName;
exports.validateContent = validateContent;
exports.reply = reply;
/* No side effect */
