// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function validateChannelName(channelName) {
  return channelName._0;
}

exports.validateChannelName = validateChannelName;
/* No side effect */
