// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Map = require("rescript/lib/js/belt_Map.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Discord_Snowflake = require("./Discord_Snowflake.bs.js");

function wrapClient(client) {
  var guilds = client.guilds;
  return {
          guilds: guilds
        };
}

function wrapGuild(guild) {
  var id = /* Snowflake */{
    _0: guild.id
  };
  var name = /* GuildName */{
    _0: guild.name
  };
  var roles = guild.roles;
  var memberCount = /* MemberCount */{
    _0: guild.memberCount
  };
  return {
          t: guild,
          id: id,
          name: name,
          memberCount: memberCount,
          roles: roles
        };
}

function wrapGuildManager(guildManager) {
  var keys = Belt_Array.map(guildManager.cache.keyArray(), (function (key) {
          return /* Snowflake */{
                  _0: key
                };
        }));
  var values = guildManager.cache.array();
  var cache = Belt_Map.fromArray(Belt_Array.zip(keys, values), Discord_Snowflake.SnowflakeCompare);
  return {
          t: guildManager,
          cache: cache
        };
}

function wrapRoleManager(roleManager) {
  var keys = Belt_Array.map(roleManager.cache.keyArray(), (function (key) {
          return /* Snowflake */{
                  _0: key
                };
        }));
  var values = roleManager.cache.array();
  var cache = Belt_Map.fromArray(Belt_Array.zip(keys, values), Discord_Snowflake.SnowflakeCompare);
  var guild = roleManager.guild;
  return {
          t: roleManager,
          cache: cache,
          guild: guild
        };
}

function wrapRole(role) {
  var name = role.name;
  return {
          t: role,
          name: /* RoleName */{
            _0: name
          }
        };
}

function wrapGuildMember(member) {
  var id = /* Snowflake */{
    _0: member.id
  };
  var roles = member.roles;
  var guild = member.guild;
  return {
          t: member,
          id: id,
          roles: roles,
          guild: guild
        };
}

function wrapGuildMemberRoleManager(guildMemberRoleManager) {
  return {
          t: guildMemberRoleManager
        };
}

function wrapMessage(message) {
  var id = message.id;
  var content = message.content;
  var author = message.author;
  var member = message.member;
  var channel = message.channel;
  var guild = message.guild;
  return {
          t: message,
          id: /* Snowflake */{
            _0: id
          },
          content: /* Content */{
            _0: content
          },
          author: author,
          member: member,
          channel: channel,
          guild: guild
        };
}

function wrapUser(user) {
  var id = /* Snowflake */{
    _0: user.id
  };
  var bot = /* Bot */{
    _0: user.bot
  };
  return {
          id: id,
          bot: bot
        };
}

function wrapChannel(channel) {
  var id = channel.id;
  var name = channel.name;
  return {
          t: channel,
          id: /* Snowflake */{
            _0: id
          },
          name: /* ChannelName */{
            _0: name
          }
        };
}

function wrapReaction(reaction) {
  var emoji = reaction.emoji;
  var message = reaction.message;
  return {
          t: reaction,
          message: message,
          emoji: emoji
        };
}

function wrapEmoji(emoji) {
  var name = /* EmojiName */{
    _0: emoji.emoji
  };
  return {
          t: emoji,
          name: name
        };
}

exports.wrapClient = wrapClient;
exports.wrapGuild = wrapGuild;
exports.wrapGuildManager = wrapGuildManager;
exports.wrapRoleManager = wrapRoleManager;
exports.wrapRole = wrapRole;
exports.wrapGuildMember = wrapGuildMember;
exports.wrapGuildMemberRoleManager = wrapGuildMemberRoleManager;
exports.wrapMessage = wrapMessage;
exports.wrapUser = wrapUser;
exports.wrapChannel = wrapChannel;
exports.wrapReaction = wrapReaction;
exports.wrapEmoji = wrapEmoji;
/* Discord_Snowflake Not a pure module */
