// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Map = require("rescript/lib/js/belt_Map.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Discord_Snowflake = require("./Discord_Snowflake.bs.js");

function wrapGuild(guild) {
  var id = /* Snowflake */{
    _0: guild.id
  };
  var name = /* GuildName */{
    _0: guild.name
  };
  var roles = guild.roles;
  return {
          t: guild,
          id: id,
          name: name,
          roles: roles
        };
}

function wrapRoleManager(roleManager) {
  var keys = Belt_Array.map(roleManager.cache.keyArray(), (function (key) {
          return /* Snowflake */{
                  _0: key
                };
        }));
  var values = roleManager.cache.array();
  var cache = Belt_Map.fromArray(Belt_Array.zip(keys, values), Discord_Snowflake.SnowflakeCompare);
  var guild = roleManager.guild;
  return {
          t: roleManager,
          cache: cache,
          guild: guild
        };
}

function wrapRole(role) {
  var name = role.name;
  return {
          t: role,
          name: /* RoleName */{
            _0: name
          }
        };
}

function wrapGuildMember(member) {
  var id = /* Snowflake */{
    _0: member.id
  };
  var roles = member.roles;
  var guild = member.guild;
  return {
          t: member,
          id: id,
          roles: roles,
          guild: guild
        };
}

function wrapGuildMemberRoleManager(guildMemberRoleManager) {
  return {
          t: guildMemberRoleManager
        };
}

function wrapMessage(message) {
  var id = message.id;
  var content = message.content;
  var author = message.author;
  var member = message.member;
  var channel = message.channel;
  var guild = message.guild;
  return {
          t: message,
          id: /* Snowflake */{
            _0: id
          },
          content: /* Content */{
            _0: content
          },
          author: author,
          member: member,
          channel: channel,
          guild: guild
        };
}

function wrapUser(user) {
  var bot = user.bot;
  return {
          bot: /* Bot */{
            _0: bot
          }
        };
}

function wrapChannel(channel) {
  var id = channel.id;
  var name = channel.name;
  return {
          t: channel,
          id: /* Snowflake */{
            _0: id
          },
          name: /* ChannelName */{
            _0: name
          }
        };
}

exports.wrapGuild = wrapGuild;
exports.wrapRoleManager = wrapRoleManager;
exports.wrapRole = wrapRole;
exports.wrapGuildMember = wrapGuildMember;
exports.wrapGuildMemberRoleManager = wrapGuildMemberRoleManager;
exports.wrapMessage = wrapMessage;
exports.wrapUser = wrapUser;
exports.wrapChannel = wrapChannel;
/* Discord_Snowflake Not a pure module */
