// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";
import * as DiscordJs from "discord.js";
import * as UpdateOrReadGistMjs from "../updateOrReadGist.mjs";

function updateGist(prim0, prim1) {
  return UpdateOrReadGistMjs.updateGist(prim0, prim1);
}

function invite(member, param, message) {
  var guild = message.guild;
  var isAdmin = member.permissions.has(DiscordJs.Permissions.FLAGS.ADMINISTRATOR);
  if (!isAdmin) {
    return message.reply("You do not have the admin privileges for this command");
  }
  var inviteCommandArray = message.content.split(" ");
  var inviteLink = Belt_Array.get(inviteCommandArray, 1);
  if (inviteLink !== undefined) {
    UpdateOrReadGistMjs.updateGist(guild.id, {
          inviteLink: inviteLink
        });
    return message.reply("Succesfully update server invite link to " + inviteLink);
  } else {
    return message.reply("Please Format your command like `!invite <invite link>`");
  }
}

export {
  updateGist ,
  invite ,
  
}
/* discord.js Not a pure module */
