// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "../../../../node_modules/rescript/lib/es6/js_dict.js";
import * as $$Promise from "../../../../node_modules/@ryyppy/rescript-promise/src/Promise.mjs";
import * as Caml_option from "../../../../node_modules/rescript/lib/es6/caml_option.js";
import * as Caml_exceptions from "../../../../node_modules/rescript/lib/es6/caml_exceptions.js";
import * as UpdateOrReadGistMjs from "../updateOrReadGist.mjs";
import * as Services_VerificationInfo from "../services/Services_VerificationInfo.mjs";

var MeHandlerError = /* @__PURE__ */Caml_exceptions.create("Handlers_Me.MeHandlerError");

function readGist(prim) {
  return UpdateOrReadGistMjs.readGist();
}

function getRolebyRoleName(guildRoleManager, roleName) {
  var guildRole = guildRoleManager.cache.find(function (role) {
        return role.name === roleName;
      });
  if (!(guildRole == null)) {
    return guildRole;
  }
  throw {
        RE_EXN_ID: MeHandlerError,
        _1: "Could not find a role with the name " + roleName,
        Error: new Error()
      };
}

function getRoleFromGuildData(data) {
  return data.role;
}

function getGuildDataFromGist(guilds, guildId, message) {
  var guildData = Js_dict.get(guilds, guildId);
  if (guildData !== undefined) {
    return Caml_option.valFromOption(guildData);
  }
  message.reply("Failed to retreive data for this Discord Guild");
  throw {
        RE_EXN_ID: MeHandlerError,
        _1: "Failed to retreive data for this Discord Guild",
        Error: new Error()
      };
}

function verifyMember(guildRole, member) {
  var guildMemberRoleManager = member.roles;
  guildMemberRoleManager.add(guildRole, "Add BrightId Verified role");
  return member.send("You are now verified", undefined);
}

function noMultipleAccounts(member) {
  member.send("You are currently limited to one Discord account with BrightID. If there has been a mistake, message the BrightID team on Discord https://discord.gg/N4ZbNjP", undefined);
  return Promise.reject({
              RE_EXN_ID: MeHandlerError,
              _1: "Verification Info can not be retrieved from more than one Discord account."
            });
}

function me(member, param, message) {
  var guild = member.guild;
  var guildRoleManager = guild.roles;
  var guildId = guild.id;
  return $$Promise.$$catch(UpdateOrReadGistMjs.readGist().then(function (guilds) {
                  var guildRole = getRolebyRoleName(guildRoleManager, getGuildDataFromGist(guilds, guildId, message).role);
                  return Services_VerificationInfo.getBrightIdVerification(member).then(function (verificationInfo) {
                              if (verificationInfo.userAddresses.length > 1) {
                                return noMultipleAccounts(member);
                              } else if (verificationInfo.userVerified) {
                                return verifyMember(guildRole, member);
                              } else {
                                member.send("You must be verified for this role", undefined);
                                return Promise.reject({
                                            RE_EXN_ID: MeHandlerError,
                                            _1: "Member is not verified"
                                          });
                              }
                            });
                }), (function (e) {
                if (e.RE_EXN_ID === MeHandlerError) {
                  console.error(e._1);
                } else if (e.RE_EXN_ID === $$Promise.JsError) {
                  var msg = e._1.message;
                  if (msg !== undefined) {
                    console.error(msg);
                  } else {
                    console.error("Must be some non-error value");
                  }
                } else {
                  console.error("Some unknown error");
                }
                return Promise.resolve(message);
              }));
}

export {
  MeHandlerError ,
  readGist ,
  getRolebyRoleName ,
  getRoleFromGuildData ,
  getGuildDataFromGist ,
  verifyMember ,
  noMultipleAccounts ,
  me ,
  
}
/* ../updateOrReadGist.mjs Not a pure module */
