// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Handlers from "../handlers/Handlers.mjs";
import * as Caml_array from "../../../../node_modules/rescript/lib/es6/caml_array.js";
import * as Belt_MapString from "../../../../node_modules/rescript/lib/es6/belt_MapString.js";
import * as Caml_exceptions from "../../../../node_modules/rescript/lib/es6/caml_exceptions.js";

var RequestHandlerError = /* @__PURE__ */Caml_exceptions.create("Parser_DetectHandler.RequestHandlerError");

var commands = [
  "!verify",
  "!me",
  "!guilds",
  "!invite",
  "!role",
  "!brightid"
];

function detectHandler(message) {
  var content = message.content;
  !content.includes("!");
  var command = Caml_array.get(content.split(" "), 0);
  var receivedHandler = Belt_MapString.get(Handlers.handlers, command);
  if (!commands.includes(command)) {
    console.error({
          RE_EXN_ID: RequestHandlerError,
          date: Date.now(),
          message: "Command not found"
        });
  }
  return receivedHandler;
}

export {
  RequestHandlerError ,
  commands ,
  detectHandler ,
  
}
/* Handlers Not a pure module */
