// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "../../../../node_modules/rescript/lib/es6/js_dict.js";
import * as Js_json from "../../../../node_modules/rescript/lib/es6/js_json.js";
import * as AuthServer from "../AuthServer.js";
import * as Belt_Option from "../../../../node_modules/rescript/lib/es6/belt_Option.js";
import * as Webapi__Fetch from "../../../../node_modules/rescript-webapi/src/Webapi/Webapi__Fetch.js";
import * as Js_null_undefined from "../../../../node_modules/rescript/lib/es6/js_null_undefined.js";

var brightIdVerificationEndpoint = "https://app.brightid.org/node/v5/verifications/Discord";

function loader(param) {
  return AuthServer.authenticator.isAuthenticated(param.request).then(function (user) {
              var init = Webapi__Fetch.RequestInit.make(/* Get */0, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined);
              return fetch(new Request(brightIdVerificationEndpoint, init)).then(function (res) {
                            return res.json();
                          }).then(function (json) {
                          var data = Belt_Option.getExn(Js_dict.get(Js_json.decodeObject(json), "data"));
                          var verificationCount = Js_null_undefined.fromOption(Belt_Option.flatMap(Js_dict.get(Js_json.decodeObject(data), "count"), Js_json.decodeNumber));
                          return Promise.resolve({
                                      user: user,
                                      verificationCount: verificationCount
                                    });
                        });
            });
}

export {
  brightIdVerificationEndpoint ,
  loader ,
  
}
/* AuthServer Not a pure module */
