// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";
import * as React from "react";
import * as Remix from "remix";
import * as AuthServer from "../AuthServer.js";
import * as Caml_option from "../../../../node_modules/rescript/lib/es6/caml_option.js";
import * as Brightid_sdk from "brightid_sdk";
import * as QrcodeReact from "qrcode.react";
import * as SidebarToggle from "../components/SidebarToggle.js";
import * as Constants$Shared from "../../node_modules/@brightidbot/shared/src/Constants.js";
import * as Caml_js_exceptions from "../../../../node_modules/rescript/lib/es6/caml_js_exceptions.js";
import * as DiscordLoginButton from "../components/DiscordLoginButton.js";
import * as DiscordLogoutButton from "../components/DiscordLogoutButton.js";
import * as Rainbowkit from "@rainbow-me/rainbowkit";

var QRCodeSvg = {};

function Root_Index$StatusToolTip(Props) {
  var statusMessage = Props.statusMessage;
  var color = Props.color;
  return React.createElement("div", {
              className: "" + color + " w-full text-center py-1"
            }, React.createElement("p", {
                  className: "text-xl font-semibold text-white"
                }, statusMessage));
}

var StatusToolTip = {
  make: Root_Index$StatusToolTip
};

function Root_Index$BrightIdToolTip(Props) {
  var fetcher = Props.fetcher;
  var match = fetcher.type;
  switch (match) {
    case "done" :
        var data = fetcher.data;
        if (data == null) {
          return React.createElement(React.Fragment, undefined);
        }
        var match$1 = data.user;
        if (match$1 == null) {
          return React.createElement(React.Fragment, undefined);
        }
        var match$2 = data.verifyStatus;
        switch (match$2) {
          case /* Unknown */0 :
              return React.createElement(Root_Index$StatusToolTip, {
                          statusMessage: "Something went wrong when checking your BrightId status",
                          color: "bg-red-600"
                        });
          case /* NotLinked */1 :
              return React.createElement(Root_Index$StatusToolTip, {
                          statusMessage: "You have not linked BrightId to Discord",
                          color: "bg-red-600"
                        });
          case /* NotVerified */2 :
              return React.createElement(Root_Index$StatusToolTip, {
                          statusMessage: "You are not Verified",
                          color: "bg-red-600"
                        });
          case /* NotSponsored */3 :
              return React.createElement(Root_Index$StatusToolTip, {
                          statusMessage: "You are not Sponsored",
                          color: "bg-red-600"
                        });
          case /* Unique */4 :
              return React.createElement(Root_Index$StatusToolTip, {
                          statusMessage: "Verified with BrightID",
                          color: "bg-green-600"
                        });
          
        }
    case "normalLoad" :
        return React.createElement(React.Fragment, undefined);
    default:
      return React.createElement(React.Fragment, undefined);
  }
}

var BrightIdToolTip = {
  make: Root_Index$BrightIdToolTip
};

function Root_Index$BrightIdVerificationActions(Props) {
  var fetcher = Props.fetcher;
  var maybeUser = Props.maybeUser;
  var maybeDeeplink = Props.maybeDeeplink;
  if (maybeUser === undefined) {
    return React.createElement(DiscordLoginButton.make, {
                label: "Login to Discord"
              });
  }
  var match = fetcher.type;
  switch (match) {
    case "done" :
        var data = fetcher.data;
        if (data == null) {
          return React.createElement(React.Fragment, undefined);
        }
        var match$1 = data.verifyStatus;
        switch (match$1) {
          case /* NotLinked */1 :
              if (maybeDeeplink !== undefined) {
                return React.createElement("div", {
                            className: "flex flex-col gap-3 items-center justify-around"
                          }, React.createElement("p", {
                                className: "text-2xl text-white"
                              }, "Scan this code in the BrightID App"), React.createElement(QrcodeReact.QRCodeSVG, {
                                value: maybeDeeplink
                              }), React.createElement("a", {
                                className: "text-white",
                                href: maybeDeeplink
                              }, "Click here for mobile"));
              } else {
                return React.createElement(Remix.Form, {
                            children: React.createElement("button", {
                                  className: "p-3 bg-transparent border-2 border-brightid font-semibold rounded-3xl text-xl text-white",
                                  type: "submit"
                                }, "Link BrightID to Discord"),
                            method: "get",
                            action: "/"
                          });
              }
          case /* NotVerified */2 :
              return React.createElement("a", {
                          className: "text-2xl",
                          href: "https://meet.brightid.org/#/",
                          target: "_blank"
                        }, React.createElement("button", {
                              className: "p-3 bg-transparent border-2 border-brightid font-semibold rounded-3xl text-xl text-white"
                            }, "Attend a Verification Party to get Verified"));
          case /* NotSponsored */3 :
              return React.createElement("a", {
                          className: "text-2xl",
                          href: "https://apps.brightid.org/",
                          target: "_blank"
                        }, React.createElement("button", {
                              className: "p-3 bg-transparent border-2 border-brightid font-semibold rounded-3xl text-xl text-white"
                            }, "Attend a Verification Party to get Verified"));
          case /* Unknown */0 :
          case /* Unique */4 :
              return React.createElement(React.Fragment, undefined);
          
        }
    case "normalLoad" :
        return React.createElement(React.Fragment, undefined);
    default:
      return React.createElement(React.Fragment, undefined);
  }
}

var BrightIdVerificationActions = {
  make: Root_Index$BrightIdVerificationActions
};

async function loader(param) {
  var maybeUser;
  var exit = 0;
  var maybeUser$1;
  try {
    maybeUser$1 = await AuthServer.authenticator.isAuthenticated(param.request);
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === "JsError") {
      maybeUser = undefined;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    maybeUser = (maybeUser$1 == null) ? undefined : Caml_option.some(maybeUser$1);
  }
  var maybeDiscordId = maybeUser !== undefined ? Caml_option.valFromOption(maybeUser).profile.id : undefined;
  if (maybeDiscordId === undefined) {
    return {
            maybeUser: maybeUser,
            maybeDeeplink: undefined
          };
  }
  var contextId = Uuid.v5(maybeDiscordId, process.env.UUID_NAMESPACE);
  var deepLink = Brightid_sdk.generateDeeplink(Constants$Shared.context, contextId, undefined);
  return {
          maybeUser: maybeUser,
          maybeDeeplink: deepLink
        };
}

function Root_Index$default(Props) {
  var context = Remix.useOutletContext();
  var fetcher = Remix.useFetcher();
  var match = Remix.useLoaderData();
  var maybeUser = match.maybeUser;
  React.useEffect((function () {
          if (fetcher.type === "init") {
            fetcher.load("/Root_FetchBrightIDDiscord");
          }
          
        }), [fetcher]);
  var match$1 = fetcher.type;
  var unusedSponsorships;
  switch (match$1) {
    case "done" :
        var data = fetcher.data;
        unusedSponsorships = (data == null) ? React.createElement("p", {
                className: "text-white"
              }, "N/A") : React.createElement("p", {
                className: "text-3xl font-semibold text-transparent bg-clip-text bg-gradient-to-l from-brightid to-white"
              }, String(data.unusedSponsorships));
        break;
    case "normalLoad" :
        unusedSponsorships = React.createElement("div", {
              className: " animate-pulse  "
            }, React.createElement("div", {
                  className: "h-8 bg-gray-300 w-8 rounded-md "
                }));
        break;
    default:
      unusedSponsorships = React.createElement("div", {
            className: " animate-pulse  "
          }, React.createElement("div", {
                className: "h-8 bg-gray-300 w-8 rounded-md "
              }));
  }
  var match$2 = fetcher.type;
  var usedSponsorships;
  switch (match$2) {
    case "done" :
        var data$1 = fetcher.data;
        usedSponsorships = (data$1 == null) ? React.createElement("p", {
                className: "text-white"
              }, "N/A") : React.createElement("p", {
                className: "text-3xl font-semibold text-transparent bg-clip-text bg-gradient-to-l from-brightid to-white"
              }, String(data$1.unusedSponsorships - data$1.assignedSponsorships | 0));
        break;
    case "normalLoad" :
        usedSponsorships = React.createElement("div", {
              className: " animate-pulse  "
            }, React.createElement("div", {
                  className: "h-8 bg-gray-300 w-8 rounded-md "
                }));
        break;
    default:
      usedSponsorships = React.createElement("div", {
            className: " animate-pulse  "
          }, React.createElement("div", {
                className: "h-8 bg-gray-300 w-8 rounded-md "
              }));
  }
  var match$3 = fetcher.type;
  var verificationCount;
  switch (match$3) {
    case "done" :
        var data$2 = fetcher.data;
        verificationCount = (data$2 == null) ? React.createElement("p", {
                className: "text-white"
              }, "N/A") : React.createElement("p", {
                className: "text-3xl font-semibold text-transparent bg-clip-text bg-gradient-to-l from-brightid to-white"
              }, String(data$2.verificationCount));
        break;
    case "normalLoad" :
        verificationCount = React.createElement("div", {
              className: " animate-pulse  "
            }, React.createElement("div", {
                  className: "h-8 bg-gray-300 w-8 rounded-md "
                }));
        break;
    default:
      verificationCount = React.createElement("div", {
            className: " animate-pulse  "
          }, React.createElement("div", {
                className: "h-8 bg-gray-300 w-8 rounded-md "
              }));
  }
  var discordLogoutButton = maybeUser !== undefined ? React.createElement(DiscordLogoutButton.make, {
          label: "Log out of Discord"
        }) : React.createElement(React.Fragment, undefined);
  return React.createElement("div", {
              className: "flex flex-col flex-1"
            }, React.createElement("section", {
                  className: "flex justify-center items-center flex-col w-full gap-4 relative"
                }, React.createElement(Root_Index$BrightIdToolTip, {
                      fetcher: fetcher
                    })), React.createElement("header", {
                  className: "flex flex-row justify-between md:justify-end m-4"
                }, React.createElement(SidebarToggle.make, {
                      handleToggleSidebar: context.handleToggleSidebar,
                      maybeUser: maybeUser
                    }), React.createElement("div", {
                      className: "flex flex-col-reverse md:flex-row items-center justify-center gap-4 "
                    }, React.createElement("div", undefined, discordLogoutButton), React.createElement(Rainbowkit.ConnectButton, {
                          className: "h-full"
                        }))), React.createElement("div", {
                  className: "flex flex-1 w-full justify-center "
                }, React.createElement("div", {
                      className: "flex flex-1 flex-col justify-around items-center text-center h-full"
                    }, React.createElement("div", undefined, React.createElement("span", {
                              className: "px-2 text-4xl md:text-6xl lg:text-8xl lg:leading-loose font-poppins font-extrabold text-transparent bg-[size:1000px_100%] bg-clip-text bg-gradient-to-l from-brightid to-white animate-textscroll "
                            }, "Unique Discord  "), React.createElement("p", {
                              className: " text-slate-300 text-4xl md:text-6xl lg:text-8xl font-poppins font-bold"
                            }, "Dashboard")), React.createElement("section", {
                          className: "width-full flex flex-col md:flex-row justify-around items-center w-full py-2"
                        }, React.createElement("div", {
                              className: "flex flex-col  rounded-xl justify-around items-center text-center "
                            }, React.createElement("div", {
                                  className: "text-2xl font-bold text-white p-2"
                                }, "Available Sponsorships"), unusedSponsorships), React.createElement("div", {
                              className: "flex flex-col rounded-xl justify-around items-center text-center px-6 py-10"
                            }, React.createElement("div", {
                                  className: "text-2xl font-bold text-white p-2"
                                }, "Verifications"), verificationCount), React.createElement("div", {
                              className: "flex flex-col rounded-xl justify-around items-center text-center"
                            }, React.createElement("div", {
                                  className: "text-2xl font-bold text-white p-2"
                                }, "Total Used Sponsors"), React.createElement("div", {
                                  className: "text-2xl font-semibold text-transparent bg-clip-text bg-gradient-to-l from-brightid to-white"
                                }, usedSponsorships))), React.createElement("section", {
                          className: "flex justify-center items-center pb-3"
                        }, React.createElement(Root_Index$BrightIdVerificationActions, {
                              fetcher: fetcher,
                              maybeUser: maybeUser,
                              maybeDeeplink: match.maybeDeeplink
                            })))));
}

var $$default = Root_Index$default;

export {
  QRCodeSvg ,
  StatusToolTip ,
  BrightIdToolTip ,
  BrightIdVerificationActions ,
  loader ,
  $$default ,
  $$default as default,
}
/* uuid Not a pure module */
