// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Handlers = require("../handlers/Handlers.bs.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var ErrorUtils = require("../error-utils");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var RequestHandlerError = /* @__PURE__ */Caml_exceptions.create("Parser_DetectHandler.RequestHandlerError");

var errorUtils = ErrorUtils;

var commands = [
  "!verify",
  "!me",
  "!guilds",
  "!invite",
  "!role",
  "!brightid"
];

function detectHandler(message) {
  var content = message.content;
  !content.includes("!");
  var command = Caml_array.get(content.split(" "), 0);
  var receivedHandler = Belt_MapString.get(Handlers.handlers, command);
  if (!commands.includes(command)) {
    console.error({
          RE_EXN_ID: RequestHandlerError,
          date: Date.now(),
          message: "Command not found"
        });
  }
  return receivedHandler;
}

exports.RequestHandlerError = RequestHandlerError;
exports.errorUtils = errorUtils;
exports.commands = commands;
exports.detectHandler = detectHandler;
/* errorUtils Not a pure module */
