// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants$Shared from "@brightidbot/shared/src/Constants.mjs";

var nodeUrl = "https:%2f%2faura-node.brightid.org";

var brightIdEndpointv5 = "https://aura-node.brightid.org/brightid/v5";

var brightIdVerificationEndpoint = brightIdEndpointv5 + "/verifications";

var brightIdSubscriptionEndpoint = brightIdEndpointv5 + "/operations";

var brightIdAppsEndpoint = brightIdEndpointv5 + "/apps";

var brightIdAppDeeplink = "brightid://link-verification/" + nodeUrl + "/" + Constants$Shared.context;

var brightIdLinkVerificationEndpoint = "https://app.brightid.org/link-verification/" + nodeUrl + "/" + Constants$Shared.context;

var nodeUrls = [
  "https://aura-node.brightid.org/brightid/v5",
  "https://app.brightid.org/node/v5"
];

var nodes = nodeUrls.map(function (url, i) {
      return {
              url: url,
              priority: i,
              timeout: 10000
            };
    });

var context = Constants$Shared.context;

export {
  context ,
  nodeUrl ,
  brightIdEndpointv5 ,
  brightIdVerificationEndpoint ,
  brightIdSubscriptionEndpoint ,
  brightIdAppsEndpoint ,
  brightIdAppDeeplink ,
  brightIdLinkVerificationEndpoint ,
  nodeUrls ,
  nodes ,
}
/* nodes Not a pure module */
