// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Constants = require("./Constants.bs.js");

var nodeUrl = "http:%2f%2fnode.brightid.org";

var brightIdEndpointv5 = "https://app.brightid.org/node/v5";

var brightIdVerificationEndpoint = brightIdEndpointv5 + "/verifications";

var brightIdSubscriptionEndpoint = brightIdEndpointv5 + "/operations";

var brightIdAppDeeplink = "brightid://link-verification/" + nodeUrl + "/" + Constants.contextId;

var brightIdLinkVerificationEndpoint = "https://app.brightid.org/link-verification/" + nodeUrl + "/" + Constants.contextId;

exports.nodeUrl = nodeUrl;
exports.brightIdEndpointv5 = brightIdEndpointv5;
exports.brightIdVerificationEndpoint = brightIdVerificationEndpoint;
exports.brightIdSubscriptionEndpoint = brightIdSubscriptionEndpoint;
exports.brightIdAppDeeplink = brightIdAppDeeplink;
exports.brightIdLinkVerificationEndpoint = brightIdLinkVerificationEndpoint;
/* No side effect */
