// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.mjs";

var nodeUrl = "http:%2f%2fnode.brightid.org";

var brightIdEndpointv5 = "https://app.brightid.org/node/v5";

var brightIdVerificationEndpoint = "" + brightIdEndpointv5 + "/verifications";

var brightIdSubscriptionEndpoint = "" + brightIdEndpointv5 + "/operations";

var brightIdAppDeeplink = "brightid://link-verification/" + nodeUrl + "/" + Constants.context + "";

var brightIdLinkVerificationEndpoint = "https://app.brightid.org/link-verification/" + nodeUrl + "/" + Constants.context + "";

var context = Constants.context;

export {
  context ,
  nodeUrl ,
  brightIdEndpointv5 ,
  brightIdVerificationEndpoint ,
  brightIdSubscriptionEndpoint ,
  brightIdAppDeeplink ,
  brightIdLinkVerificationEndpoint ,
}
/* No side effect */
