// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dotenv from "dotenv";
import * as Js_dict from "../../../node_modules/rescript/lib/es6/js_dict.js";
import * as FindUp from "find-up";
import * as Process from "process";

var nodeEnv = Process.env;

function createEnv(param) {
  var envFile = Js_dict.get(nodeEnv, "ENV_FILE");
  var path = envFile !== undefined ? FindUp.findUpSync(envFile, undefined) : FindUp.findUpSync(".env.local", undefined);
  Dotenv.config({
        path: path
      });
  
}

function env(name) {
  var value = Js_dict.get(nodeEnv, name);
  if (value !== undefined) {
    return {
            TAG: /* Ok */0,
            _0: value
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: "Environment variable " + name + " is missing"
          };
  }
}

function getConfig(param) {
  var match = env("DISCORD_API_TOKEN");
  var match$1 = env("UUID_NAMESPACE");
  if (match.TAG === /* Ok */0) {
    if (match$1.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: {
                discordApiToken: match._0,
                uuidNamespace: match$1._0
              }
            };
    } else {
      return match$1;
    }
  } else {
    return match;
  }
}

export {
  nodeEnv ,
  createEnv ,
  env ,
  getConfig ,
  
}
/* nodeEnv Not a pure module */
