// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var BrightIdError = /* @__PURE__ */Caml_exceptions.create("Exceptions.BrightIdError");

var VerifyCommandError = /* @__PURE__ */Caml_exceptions.create("Exceptions.VerifyCommandError");

var InviteCommandError = /* @__PURE__ */Caml_exceptions.create("Exceptions.InviteCommandError");

var ButtonVerifyHandlerError = /* @__PURE__ */Caml_exceptions.create("Exceptions.ButtonVerifyHandlerError");

var SponsorButtonError = /* @__PURE__ */Caml_exceptions.create("Exceptions.SponsorButtonError");

var PremiumSponsorButtonError = /* @__PURE__ */Caml_exceptions.create("Exceptions.PremiumSponsorButtonError");

function isUnverifiedError(error) {
  if (error.error) {
    if (error.code === 403 && (error.errorNum === 2 || error.errorNum === 3 || error.errorNum === 4)) {
      return true;
    } else if (error.code === 404) {
      return error.errorNum === 2;
    } else {
      return false;
    }
  } else {
    return false;
  }
}

export {
  BrightIdError ,
  VerifyCommandError ,
  InviteCommandError ,
  ButtonVerifyHandlerError ,
  SponsorButtonError ,
  PremiumSponsorButtonError ,
  isUnverifiedError ,
}
/* No side effect */
