// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Exceptions from "./Exceptions.mjs";
import NodeFetch from "node-fetch";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Decode$Shared from "@brightidbot/shared/src/Decode.mjs";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.mjs";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.mjs";

var NoRes = /* @__PURE__ */Caml_exceptions.create("FetchTools.NoRes");

var HttpError = /* @__PURE__ */Caml_exceptions.create("FetchTools.HttpError");

async function fetchWithFallback(relativeUrl, defaultNode, fallbackNodes) {
  var nodes = defaultNode !== undefined ? Belt_Array.concatMany([
          [defaultNode],
          fallbackNodes.filter(function (other) {
                return other.url !== defaultNode.url;
              })
        ]) : fallbackNodes;
  var attempt = async function (index) {
    var node = nodes[index];
    if (node !== undefined) {
      try {
        var timeout = Core__Option.getOr(node.timeout, 10000);
        var response = await NodeFetch(node.url + relativeUrl, {
              timeout: timeout,
              method: "GET",
              headers: {
                "Content-Type": "application/json",
                Accept: "application/json"
              }
            });
        var status = response.status;
        if (status >= 500 || status === 429) {
          throw {
                RE_EXN_ID: HttpError,
                _1: status,
                Error: new Error()
              };
        }
        return Caml_option.some(response);
      }
      catch (exn){
        return await attempt(index + 1 | 0);
      }
    } else {
      throw {
            RE_EXN_ID: NoRes,
            Error: new Error()
          };
    }
  };
  return await attempt(0);
}

function decodeResponse(json, decoder) {
  var error = Json$JsonCombinators.decode(json, Decode$Shared.Decode_BrightId.$$Error.data);
  if (error.TAG === "Ok") {
    var error$1 = error._0;
    if (error$1.error && (error$1.code >= 500 || error$1.code === 429)) {
      throw {
            RE_EXN_ID: HttpError,
            _1: error$1.code,
            Error: new Error()
          };
    }
    if (error$1.error) {
      throw {
            RE_EXN_ID: Exceptions.BrightIdError,
            _1: error$1,
            Error: new Error()
          };
    }

  }
  var data = Json$JsonCombinators.decode(json, decoder);
  if (data.TAG === "Ok") {
    return data._0;
  }
  throw {
        RE_EXN_ID: Json_Decode$JsonCombinators.DecodeError,
        _1: data._0,
        Error: new Error()
      };
}

async function fetchJson(relativeUrl, nodes) {
  var response = await fetchWithFallback(relativeUrl, nodes[0], nodes);
  var response$1;
  if (response !== undefined) {
    response$1 = Caml_option.valFromOption(response);
  } else {
    throw {
          RE_EXN_ID: NoRes,
          Error: new Error()
        };
  }
  var json = await response$1.json();
  var status = response$1.status;
  if (status >= 400) {
    var error = Json$JsonCombinators.decode(json, Decode$Shared.Decode_BrightId.$$Error.data);
    if (error.TAG === "Ok") {
      var error$1 = error._0;
      if (error$1.error && error$1.code === status) {
        throw {
              RE_EXN_ID: Exceptions.BrightIdError,
              _1: error$1,
              Error: new Error()
            };
      }
      throw {
            RE_EXN_ID: HttpError,
            _1: status,
            Error: new Error()
          };
    }
    throw {
          RE_EXN_ID: HttpError,
          _1: status,
          Error: new Error()
        };
  }
  return json;
}

export {
  NoRes ,
  HttpError ,
  fetchWithFallback ,
  decodeResponse ,
  fetchJson ,
}
/* node-fetch Not a pure module */
