// Generated by ReScript, PLEASE EDIT WITH CARE


function nowInSeconds() {
  return Date.now() / 1000.0 | 0;
}

function fifteenMinutesFromNow() {
  return nowInSeconds() + 900 | 0;
}

export {
  nowInSeconds ,
  fifteenMinutesFromNow ,
}
/* No side effect */
