// Generated by ReScript, PLEASE EDIT WITH CARE


var ContextId = {};

var App = {};

var $$Error = {};

var Gist = {};

var Sponsorships = {};

var Operations = {};

var SPContract = {};

export {
  ContextId ,
  App ,
  $$Error ,
  Gist ,
  Sponsorships ,
  Operations ,
  SPContract ,
}
/* No side effect */
