// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Remix from "remix";

function AdminButton(Props) {
  var guildId = Props.guildId;
  return React.createElement(Remix.Link, {
              prefetch: "intent",
              to: "/guilds/" + guildId + "/admin",
              children: React.createElement("button", {
                    className: "p-4 bg-transparent border-2 border-brightid font-semibold rounded-3xl text-large text-white"
                  }, "Admin Settings")
            });
}

var make = AdminButton;

export {
  make ,
}
/* react Not a pure module */
