// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@remix-run/react";

function DiscordLoginButton(props) {
  return React.createElement(React$1.Form, {
              children: React.createElement("button", {
                    className: "w-full p-6 bg-discord font-bold rounded-xl text-2xl text-white"
                  }, props.label),
              method: "post",
              action: "/auth/discord"
            });
}

var make = DiscordLoginButton;

export {
  make ,
}
/* react Not a pure module */
