// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Remix from "remix";

function DiscordLogoutButton(Props) {
  var label = Props.label;
  return React.createElement(Remix.Form, {
              children: React.createElement("button", {
                    className: "w-full p-2 bg-red-600 font-bold rounded-xl text-xl text-white",
                    onClick: (function (param) {
                        ((window.location.reload()));
                      })
                  }, label),
              method: "post",
              action: "/auth/discordLogout"
            });
}

var make = DiscordLogoutButton;

export {
  make ,
}
/* react Not a pure module */
