// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@remix-run/react";
import * as JsxRuntime from "react/jsx-runtime";

function DiscordLoginButton(props) {
  return JsxRuntime.jsx(React.Form, {
              children: JsxRuntime.jsx("button", {
                    children: props.label,
                    className: "w-full p-6 bg-discord font-bold rounded-xl text-2xl text-white"
                  }),
              method: "post",
              action: "/auth/discord"
            });
}

var make = DiscordLoginButton;

export {
  make ,
}
/* @remix-run/react Not a pure module */
