// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";
import * as Caml_option from "../../../../node_modules/rescript/lib/es6/caml_option.js";
import * as InviteButton from "./InviteButton.js";
import * as React$1 from "@remix-run/react";
import * as ReactProSidebar from "react-pro-sidebar";
import * as JsxPPXReactSupport from "../../../../node_modules/rescript/lib/es6/jsxPPXReactSupport.js";

var ConnectButton = {};

function Sidebar(props) {
  var guilds = props.guilds;
  var icon = function (param) {
    var icon$1 = param.icon;
    if (icon$1 !== undefined) {
      return "https://cdn.discordapp.com/icons/" + param.id + "/" + icon$1 + ".png";
    } else {
      return "/assets/brightid_logo_white.png";
    }
  };
  var sidebarElements;
  if (props.loadingGuilds) {
    var intersection = Belt_Array.map(guilds, (function (guild) {
            return JsxPPXReactSupport.createElementWithKey(guild.id, ReactProSidebar.Menu, {
                        children: Caml_option.some(React.createElement(ReactProSidebar.MenuItem, {
                                  children: Caml_option.some(React.createElement(React$1.Link, {
                                            className: "font-semibold text-xl",
                                            prefetch: "intent",
                                            to: "/guilds/" + guild.id + "",
                                            children: guild.name
                                          })),
                                  className: "bg-extraDark",
                                  icon: Caml_option.some(React.createElement("img", {
                                            className: " bg-extraDark rounded-lg border-1 border-white",
                                            src: icon(guild)
                                          }))
                                })),
                        iconShape: "square"
                      });
          }));
    var loading = Belt_Array.map(Belt_Array.range(0, 4), (function (i) {
            return JsxPPXReactSupport.createElementWithKey(String(i + 1 | 0), ReactProSidebar.Menu, {
                        children: Caml_option.some(React.createElement(ReactProSidebar.MenuItem, {
                                  children: Caml_option.some(React.createElement("div", {
                                            className: "flex flex-col space-y-3"
                                          }, React.createElement("div", {
                                                className: "w-36 bg-gray-300 h-6 rounded-md "
                                              }))),
                                  className: "flex animate-pulse flex-row h-full bg-extraDark ",
                                  icon: Caml_option.some(React.createElement("img", {
                                            className: " bg-extraDark  rounded-lg",
                                            src: "/assets/brightid_logo_white.png"
                                          }))
                                })),
                        iconShape: "square"
                      });
          }));
    sidebarElements = Belt_Array.concat(intersection, loading);
  } else if (guilds.length !== 0) {
    var match = guilds.length;
    sidebarElements = match !== 0 ? Belt_Array.map(guilds, (function (guild) {
              return JsxPPXReactSupport.createElementWithKey(guild.id, ReactProSidebar.Menu, {
                          children: Caml_option.some(React.createElement(ReactProSidebar.MenuItem, {
                                    children: Caml_option.some(React.createElement(React$1.Link, {
                                              className: "font-semibold text-xl",
                                              prefetch: "intent",
                                              to: "/guilds/" + guild.id + "",
                                              children: guild.name
                                            })),
                                    className: "bg-extraDark",
                                    icon: Caml_option.some(React.createElement("img", {
                                              className: " bg-extraDark rounded-lg border-1 border-white",
                                              src: icon(guild)
                                            }))
                                  })),
                          iconShape: "square"
                        });
            })) : React.createElement("p", {
            className: "text-white"
          }, "No Guilds");
  } else {
    sidebarElements = React.createElement("p", {
          className: "text-white"
        }, "Couldn't Load Discord Servers");
  }
  return React.createElement(ReactProSidebar.ProSidebar, {
              children: null,
              className: "bg-dark scrollbar-hide",
              breakPoint: "md",
              onToggle: props.handleToggleSidebar,
              toggled: props.toggled
            }, React.createElement(ReactProSidebar.SidebarHeader, {
                  children: Caml_option.some(React.createElement(InviteButton.make, {})),
                  className: "p-2 flex justify-around items-center top-0 sticky bg-dark z-10 scrollbar-hide"
                }), React.createElement(ReactProSidebar.SidebarContent, {
                  children: null,
                  className: "scrollbar-hide"
                }, JsxPPXReactSupport.createElementWithKey(String(0), ReactProSidebar.Menu, {
                      iconShape: "square"
                    }), sidebarElements), React.createElement(ReactProSidebar.SidebarFooter, {
                  children: Caml_option.some(React.createElement(React$1.Link, {
                            to: "",
                            children: React.createElement(ReactProSidebar.MenuItem, {
                                  children: Caml_option.some(React.createElement("img", {
                                            src: "/assets/brightid_reversed.svg"
                                          }))
                                })
                          })),
                  className: "bg-extraDark bottom-0 sticky scrollbar-hide list-none"
                }));
}

var make = Sidebar;

export {
  ConnectButton ,
  make ,
}
/* react Not a pure module */
