// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Option from "../../../../node_modules/rescript/lib/es6/belt_Option.js";
import * as Fa from "react-icons/fa";
import * as JsxRuntime from "react/jsx-runtime";

function SidebarToggle(props) {
  var handleToggleSidebar = props.handleToggleSidebar;
  var visibility = Belt_Option.isSome(props.maybeUser) ? "visible" : "invisible";
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Fa.FaBars, {
                    size: 30
                  }),
              className: "" + visibility + " md:hidden cursor-pointer w-12 h-12 bg-dark text-center text-white rounded-full flex justify-center items-center font-xl",
              onClick: (function (param) {
                  Curry._1(handleToggleSidebar, true);
                })
            });
}

var make = SidebarToggle;

export {
  make ,
}
/* react-icons/fa Not a pure module */
