// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SubmitPopup(props) {
  var visibilty = props.hasChangesToSave ? "visible" : "invisible";
  return React.createElement("div", {
              className: "p-4 w-full bottom-0 absolute bg-extraDark rounded-xl shadow-2xl " + visibilty + ""
            }, React.createElement("div", {
                  className: "flex flex-row justify-between items-center"
                }, React.createElement("p", undefined, "Careful - You have unsaved changes!"), React.createElement("div", {
                      className: "flex flex-row items-center gap-4"
                    }, React.createElement("div", {
                          className: "text-xl",
                          onClick: props.reset
                        }, "Reset"), React.createElement("button", {
                          className: "bg-brightid p-3 rounded-xl text-xl font-semibold",
                          type: "submit"
                        }, "Save Changes"))));
}

var make = SubmitPopup;

export {
  make ,
}
/* react Not a pure module */
