// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuthServer from "../../AuthServer.js";

function action(param) {
  return AuthServer.authenticator.logout(param.request, {
              redirectTo: "/"
            });
}

export {
  action ,
}
/* AuthServer Not a pure module */
