// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Env = require("./Env.bs.js");
var Dotenv = require("dotenv");
var DiscordJs = require("discord.js");

Dotenv.config();

var config = Env.getConfig(undefined);

var client = new DiscordJs.Client();

client.on("ready", (function (param) {
        console.log("Logged In");
        
      }));

if (config.TAG === /* Ok */0) {
  client.login(config._0);
} else {
  console.log(config._0);
}

exports.config = config;
exports.client = client;
/*  Not a pure module */
