// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Process = require("process");

var nodeEnv = Process.env;

function env(name) {
  var value = Js_dict.get(nodeEnv, name);
  if (value !== undefined) {
    return {
            TAG: /* Ok */0,
            _0: value
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: "Environment variable " + name + " is missing"
          };
  }
}

function getConfig(param) {
  var match = env("DISCORD_API_TOKEN");
  var match$1 = env("UUID_NAMESPACE");
  if (match.TAG === /* Ok */0) {
    if (match$1.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: {
                discordApiToken: /* DiscordToken */{
                  _0: match._0
                },
                uuidNamespace: /* UUIDNamespace */{
                  _0: match$1._0
                }
              }
            };
    } else {
      return match$1;
    }
  } else {
    return match;
  }
}

exports.nodeEnv = nodeEnv;
exports.env = env;
exports.getConfig = getConfig;
/* nodeEnv Not a pure module */
